###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.

See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [49]:
import numpy as np
a = np.array([[92,90,74],
    [6,63,93],
    [15,93,96],
    [70,60,48]])
a

array([[92, 90, 74],
       [ 6, 63, 93],
       [15, 93, 96],
       [70, 60, 48]])

In [6]:
np.sort(a)

array([[74, 90, 92],
       [ 6, 63, 93],
       [15, 93, 96],
       [48, 60, 70]])

In [17]:
# ii. based on 2nd column

a[np.argsort(a[:,1])]

array([[70, 60, 48],
       [ 6, 63, 93],
       [92, 90, 74],
       [15, 93, 96]])

In [32]:
# iii. based on row max- ascending

a[np.argsort(np.max(a, axis=1))[::-1]]

array([[15, 93, 96],
       [ 6, 63, 93],
       [92, 90, 74],
       [70, 60, 48]])

In [50]:
# iv. based on elements value

np.sort(a, axis=None).reshape(4,3)

array([[ 6, 15, 48],
       [60, 63, 70],
       [74, 90, 92],
       [93, 93, 96]])

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [98]:
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])
marks

array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])

In [99]:
# i. Add marks every student of an extra subject in the same array.
extra_subject = np.array([41, 87, 72, 36, 92]).reshape(5,1)
marks = np.append(marks, extra_subject, axis=1)
marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [100]:
# ii.

rec1 = np.array([77, 83, 98, 95, 89]).reshape(1,5)
rec2 = np.array([92, 71, 52, 61, 53]).reshape(1,5)

marks = np.concatenate([marks, rec1, rec2], axis=0)
marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [101]:
# iii. Add extra column with sum of all subjects(5-subjects) marks

total = np.sum(marks, axis = 1).reshape(7,1)
marks = np.append(marks, total, axis=1)
marks

array([[ 13,  10,   9,  33,  41, 106],
       [ 63,  46,  90,  42,  87, 328],
       [ 39,  76,  13,  29,  72, 229],
       [ 82,   9,  29,  78,  36, 234],
       [ 67,  61,  59,  36,  92, 315],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

In [127]:
# iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

marks[np.argsort(marks[:,-1:],axis=0)[::-1]].reshape(7,6)

array([[ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329],
       [ 63,  46,  90,  42,  87, 328],
       [ 67,  61,  59,  36,  92, 315],
       [ 82,   9,  29,  78,  36, 234],
       [ 39,  76,  13,  29,  72, 229],
       [ 13,  10,   9,  33,  41, 106]])

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [130]:
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

print(np.unique(arr, axis=0))
print(np.unique(arr, axis=1))

[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]

###`Q-4:` Flip given 2-D array along both axes at the same time.

In [132]:
print(arr)
np.flip(arr)

[[1 2 3 3 1 1]
 [0 9 1 2 8 8]
 [1 2 3 8 8 8]
 [1 2 3 3 1 1]]

array([[1, 1, 3, 3, 2, 1],
       [8, 8, 8, 3, 2, 1],
       [8, 8, 2, 1, 9, 0],
       [1, 1, 3, 3, 2, 1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [138]:
a = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])
X = 6
np.unique(np.where(a>X)[0])

array([1, 3])

### `Q-6:` How to convert an array of arrays into a flat 1d array?

In [159]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

np.concatenate([arr1,arr2,arr3])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [160]:
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))

In [161]:
arr

array([[448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
        387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
        277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
        997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
        645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
        957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
        244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
        270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265,
        503, 320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123,
        946, 587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514,
        296, 879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658,
        528, 395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711,
        800, 976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490,
        803, 621, 453, 193, 607, 677, 637, 728, 724, 534, 748, 291, 194,
        761, 875, 687, 569, 228, 482, 781, 554, 654, 739, 885, 197, 266,
        228, 892, 207, 883, 588]])

In [162]:
np.delete(arr, [np.argmin(arr), np.argmax(arr)])

array([448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
       387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
       277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
       997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
       645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
       957, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464, 244,
       782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771, 270,
       308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 265, 503, 320,
       230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123, 946, 587,
       227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514, 296, 879,
       575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658, 528, 395,
       525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711, 800, 976,
       786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490, 803, 621,
       453, 193, 607, 677, 637, 728, 724, 534, 748, 291, 194, 761, 875,
       687, 569, 228, 482, 781, 554, 654, 739, 885, 197, 266, 228, 892,
       207, 883, 588])

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [179]:
arr = np.arange(1000)
print(arr)
lim_arr = np.clip(arr, a_min=100, a_max=200)
print(lim_arr)
np.cumsum(np.sort(lim_arr))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827
 828 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845
 846 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863
 864 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881
 882 883 884 885 886 887 888 889 890 891 892 893 894 895 896 897 898 899
 900 901 902 903 904 905 906 907 908 909 910 911 912 913 914 915 916 917
 918 919 920 921 922 923 924 925 926 927 928 929 930 931 932 933 934 935
 936 937 938 939 940 941 942 943 944 945 946 947 948 949 950 951 952 953
 954 955 956 957 958 959 960 961 962 963 964 965 966 967 968 969 970 971
 972 973 974 975 976 977 978 979 980 981 982 983 984 985 986 987 988 989
 990 991 992 993 994 995 996 997 998 999]
[100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100 100 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200]

array([   100,    200,    300,    400,    500,    600,    700,    800,
          900,   1000,   1100,   1200,   1300,   1400,   1500,   1600,
         1700,   1800,   1900,   2000,   2100,   2200,   2300,   2400,
         2500,   2600,   2700,   2800,   2900,   3000,   3100,   3200,
         3300,   3400,   3500,   3600,   3700,   3800,   3900,   4000,
         4100,   4200,   4300,   4400,   4500,   4600,   4700,   4800,
         4900,   5000,   5100,   5200,   5300,   5400,   5500,   5600,
         5700,   5800,   5900,   6000,   6100,   6200,   6300,   6400,
         6500,   6600,   6700,   6800,   6900,   7000,   7100,   7200,
         7300,   7400,   7500,   7600,   7700,   7800,   7900,   8000,
         8100,   8200,   8300,   8400,   8500,   8600,   8700,   8800,
         8900,   9000,   9100,   9200,   9300,   9400,   9500,   9600,
         9700,   9800,   9900,  10000,  10100,  10201,  10303,  10406,
        10510,  10615,  10721,  10828,  10936,  11045,  11155,  11266,
        11378,  11491,  11605,  11720,  11836,  11953,  12071,  12190,
        12310,  12431,  12553,  12676,  12800,  12925,  13051,  13178,
        13306,  13435,  13565,  13696,  13828,  13961,  14095,  14230,
        14366,  14503,  14641,  14780,  14920,  15061,  15203,  15346,
        15490,  15635,  15781,  15928,  16076,  16225,  16375,  16526,
        16678,  16831,  16985,  17140,  17296,  17453,  17611,  17770,
        17930,  18091,  18253,  18416,  18580,  18745,  18911,  19078,
        19246,  19415,  19585,  19756,  19928,  20101,  20275,  20450,
        20626,  20803,  20981,  21160,  21340,  21521,  21703,  21886,
        22070,  22255,  22441,  22628,  22816,  23005,  23195,  23386,
        23578,  23771,  23965,  24160,  24356,  24553,  24751,  24950,
        25150,  25350,  25550,  25750,  25950,  26150,  26350,  26550,
        26750,  26950,  27150,  27350,  27550,  27750,  27950,  28150,
        28350,  28550,  28750,  28950,  29150,  29350,  29550,  29750,
        29950,  30150,  30350,  30550,  30750,  30950,  31150,  31350,
        31550,  31750,  31950,  32150,  32350,  32550,  32750,  32950,
        33150,  33350,  33550,  33750,  33950,  34150,  34350,  34550,
        34750,  34950,  35150,  35350,  35550,  35750,  35950,  36150,
        36350,  36550,  36750,  36950,  37150,  37350,  37550,  37750,
        37950,  38150,  38350,  38550,  38750,  38950,  39150,  39350,
        39550,  39750,  39950,  40150,  40350,  40550,  40750,  40950,
        41150,  41350,  41550,  41750,  41950,  42150,  42350,  42550,
        42750,  42950,  43150,  43350,  43550,  43750,  43950,  44150,
        44350,  44550,  44750,  44950,  45150,  45350,  45550,  45750,
        45950,  46150,  46350,  46550,  46750,  46950,  47150,  47350,
        47550,  47750,  47950,  48150,  48350,  48550,  48750,  48950,
        49150,  49350,  49550,  49750,  49950,  50150,  50350,  50550,
        50750,  50950,  51150,  51350,  51550,  51750,  51950,  52150,
        52350,  52550,  52750,  52950,  53150,  53350,  53550,  53750,
        53950,  54150,  54350,  54550,  54750,  54950,  55150,  55350,
        55550,  55750,  55950,  56150,  56350,  56550,  56750,  56950,
        57150,  57350,  57550,  57750,  57950,  58150,  58350,  58550,
        58750,  58950,  59150,  59350,  59550,  59750,  59950,  60150,
        60350,  60550,  60750,  60950,  61150,  61350,  61550,  61750,
        61950,  62150,  62350,  62550,  62750,  62950,  63150,  63350,
        63550,  63750,  63950,  64150,  64350,  64550,  64750,  64950,
        65150,  65350,  65550,  65750,  65950,  66150,  66350,  66550,
        66750,  66950,  67150,  67350,  67550,  67750,  67950,  68150,
        68350,  68550,  68750,  68950,  69150,  69350,  69550,  69750,
        69950,  70150,  70350,  70550,  70750,  70950,  71150,  71350,
        71550,  71750,  71950,  72150,  72350,  72550,  72750,  72950,
        73150,  73350,  73550,  73750,  73950,  74150,  74350,  74550,
        74750,  74950,  75150,  75350,  75550,  75750,  75950,  76150,
        76350,  76550,  76750,  76950,  77150,  77350,  77550,  77750,
        77950,  78150,  78350,  78550,  78750,  78950,  79150,  79350,
        79550,  79750,  79950,  80150,  80350,  80550,  80750,  80950,
        81150,  81350,  81550,  81750,  81950,  82150,  82350,  82550,
        82750,  82950,  83150,  83350,  83550,  83750,  83950,  84150,
        84350,  84550,  84750,  84950,  85150,  85350,  85550,  85750,
        85950,  86150,  86350,  86550,  86750,  86950,  87150,  87350,
        87550,  87750,  87950,  88150,  88350,  88550,  88750,  88950,
        89150,  89350,  89550,  89750,  89950,  90150,  90350,  90550,
        90750,  90950,  91150,  91350,  91550,  91750,  91950,  92150,
        92350,  92550,  92750,  92950,  93150,  93350,  93550,  93750,
        93950,  94150,  94350,  94550,  94750,  94950,  95150,  95350,
        95550,  95750,  95950,  96150,  96350,  96550,  96750,  96950,
        97150,  97350,  97550,  97750,  97950,  98150,  98350,  98550,
        98750,  98950,  99150,  99350,  99550,  99750,  99950, 100150,
       100350, 100550, 100750, 100950, 101150, 101350, 101550, 101750,
       101950, 102150, 102350, 102550, 102750, 102950, 103150, 103350,
       103550, 103750, 103950, 104150, 104350, 104550, 104750, 104950,
       105150, 105350, 105550, 105750, 105950, 106150, 106350, 106550,
       106750, 106950, 107150, 107350, 107550, 107750, 107950, 108150,
       108350, 108550, 108750, 108950, 109150, 109350, 109550, 109750,
       109950, 110150, 110350, 110550, 110750, 110950, 111150, 111350,
       111550, 111750, 111950, 112150, 112350, 112550, 112750, 112950,
       113150, 113350, 113550, 113750, 113950, 114150, 114350, 114550,
       114750, 114950, 115150, 115350, 115550, 115750, 115950, 116150,
       116350, 116550, 116750, 116950, 117150, 117350, 117550, 117750,
       117950, 118150, 118350, 118550, 118750, 118950, 119150, 119350,
       119550, 119750, 119950, 120150, 120350, 120550, 120750, 120950,
       121150, 121350, 121550, 121750, 121950, 122150, 122350, 122550,
       122750, 122950, 123150, 123350, 123550, 123750, 123950, 124150,
       124350, 124550, 124750, 124950, 125150, 125350, 125550, 125750,
       125950, 126150, 126350, 126550, 126750, 126950, 127150, 127350,
       127550, 127750, 127950, 128150, 128350, 128550, 128750, 128950,
       129150, 129350, 129550, 129750, 129950, 130150, 130350, 130550,
       130750, 130950, 131150, 131350, 131550, 131750, 131950, 132150,
       132350, 132550, 132750, 132950, 133150, 133350, 133550, 133750,
       133950, 134150, 134350, 134550, 134750, 134950, 135150, 135350,
       135550, 135750, 135950, 136150, 136350, 136550, 136750, 136950,
       137150, 137350, 137550, 137750, 137950, 138150, 138350, 138550,
       138750, 138950, 139150, 139350, 139550, 139750, 139950, 140150,
       140350, 140550, 140750, 140950, 141150, 141350, 141550, 141750,
       141950, 142150, 142350, 142550, 142750, 142950, 143150, 143350,
       143550, 143750, 143950, 144150, 144350, 144550, 144750, 144950,
       145150, 145350, 145550, 145750, 145950, 146150, 146350, 146550,
       146750, 146950, 147150, 147350, 147550, 147750, 147950, 148150,
       148350, 148550, 148750, 148950, 149150, 149350, 149550, 149750,
       149950, 150150, 150350, 150550, 150750, 150950, 151150, 151350,
       151550, 151750, 151950, 152150, 152350, 152550, 152750, 152950,
       153150, 153350, 153550, 153750, 153950, 154150, 154350, 154550,
       154750, 154950, 155150, 155350, 155550, 155750, 155950, 156150,
       156350, 156550, 156750, 156950, 157150, 157350, 157550, 157750,
       157950, 158150, 158350, 158550, 158750, 158950, 159150, 159350,
       159550, 159750, 159950, 160150, 160350, 160550, 160750, 160950,
       161150, 161350, 161550, 161750, 161950, 162150, 162350, 162550,
       162750, 162950, 163150, 163350, 163550, 163750, 163950, 164150,
       164350, 164550, 164750, 164950, 165150, 165350, 165550, 165750,
       165950, 166150, 166350, 166550, 166750, 166950, 167150, 167350,
       167550, 167750, 167950, 168150, 168350, 168550, 168750, 168950,
       169150, 169350, 169550, 169750, 169950, 170150, 170350, 170550,
       170750, 170950, 171150, 171350, 171550, 171750, 171950, 172150,
       172350, 172550, 172750, 172950, 173150, 173350, 173550, 173750,
       173950, 174150, 174350, 174550, 174750, 174950, 175150, 175350,
       175550, 175750, 175950, 176150, 176350, 176550, 176750, 176950,
       177150, 177350, 177550, 177750, 177950, 178150, 178350, 178550,
       178750, 178950, 179150, 179350, 179550, 179750, 179950, 180150,
       180350, 180550, 180750, 180950, 181150, 181350, 181550, 181750,
       181950, 182150, 182350, 182550, 182750, 182950, 183150, 183350,
       183550, 183750, 183950, 184150, 184350, 184550, 184750, 184950])

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [183]:
a = np.random.random(100)
a_round = np.round_(a, decimals=3)
a_round

array([0.125, 0.919, 0.665, 0.292, 0.435, 0.179, 0.258, 0.434, 0.546,
       0.015, 0.381, 0.188, 0.663, 0.947, 0.542, 0.699, 0.188, 0.992,
       0.285, 0.808, 0.937, 0.465, 0.772, 0.733, 0.528, 0.787, 0.02 ,
       0.146, 0.703, 0.475, 0.325, 0.863, 0.485, 0.761, 0.433, 0.07 ,
       0.274, 0.703, 0.671, 0.299, 0.308, 0.507, 0.729, 0.057, 0.784,
       0.084, 0.527, 0.671, 0.056, 0.797, 0.553, 0.771, 0.701, 0.965,
       0.348, 0.034, 0.676, 0.238, 0.513, 0.576, 0.626, 0.556, 0.175,
       0.987, 0.838, 0.982, 0.953, 0.652, 0.987, 0.584, 0.444, 0.162,
       0.377, 0.965, 0.784, 0.936, 0.314, 0.144, 0.668, 0.162, 0.107,
       0.758, 0.524, 0.382, 0.014, 0.711, 0.403, 0.807, 0.723, 0.825,
       0.207, 0.973, 0.318, 0.726, 0.963, 0.724, 0.521, 0.3  , 0.205,
       0.263])

In [187]:
print(np.percentile(a_round,0))
print(np.min(a_round))

0.014
0.014

In [188]:
print(np.max(a_round))
np.percentile(a_round,100)

0.992

0.992

In [191]:
print(np.percentile(a_round,50))
print(np.percentile(a_round,51))
result = np.percentile(a_round,51)-np.percentile(a_round,50)
print("difference is --> ", np.round(result, decimals=3))

0.535
0.54396
difference is -->  0.009